package com.assignment.expense_tracker.controller;

import com.assignment.expense_tracker.dto.CategoryTotalDTO;
import com.assignment.expense_tracker.dto.ExpenseDTO;
import com.assignment.expense_tracker.enums.ExpenseSortField;
import com.assignment.expense_tracker.service.ExpenseService;
import io.swagger.v3.oas.annotations.Operation;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;

import java.util.List;

@RestController
@RequestMapping("/api/expenses")
@RequiredArgsConstructor
@Slf4j
@Validated
public class ExpenseController {

    private final ExpenseService expenseService;

    @Operation(
            summary = "Create a new expense",
            description = "Creates a new expense record using the provided details. The ID is generated by the system."
    )
    @PostMapping
    public ResponseEntity<ExpenseDTO> create(@Valid @RequestBody ExpenseDTO dto) {
        log.info("Creating expense: {}", dto);
        ExpenseDTO created = expenseService.createExpense(dto);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @Operation(
            summary = "List expenses",
            description = "Fetches a paginated list of expenses with optional sorting by fields like amount or date."
    )
    @GetMapping
    public ResponseEntity<Page<ExpenseDTO>> list(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size,
            @RequestParam(defaultValue = "NONE") ExpenseSortField sortBy) {
        log.info("Fetching expenses, page={}, size={}, sortBy={}", page, size, sortBy);
        return ResponseEntity.ok(expenseService.listExpenses(page, size, sortBy));
    }

    @Operation(
            summary = "Update an existing expense",
            description = "Updates an expense identified by its ID."
    )
    @PutMapping
    public ResponseEntity<ExpenseDTO> update(@Valid @RequestBody ExpenseDTO dto) {
        log.info("Updating expense with data={}", dto);
        return ResponseEntity.ok(expenseService.updateExpense(dto));
    }

    @Operation(
            summary = "Get top N spending categories",
            description = "Returns the top N categories ranked by total spending amount. The value of N must be between 1 and 10."
    )
    @GetMapping("/top")
    public ResponseEntity<List<CategoryTotalDTO>> top(@RequestParam(defaultValue = "3")
                                                      @Min(value = 1, message = "limit must be at least 1")
                                                      @Max(value = 10, message = "limit cannot exceed 10")
                                                      int limit) {
        log.info("Fetching top {} categories", limit);
        return ResponseEntity.ok(expenseService.topCategories(limit));
    }
}

